#!/usr/bin/env python3
"""Reproduce every printed number in Causal Reasoning with Statistics.

Three stages, all offline and all with free software:

  1. Regenerate the ten synthetic datasets from their seeded generators and
     confirm that the regenerated files are byte-for-byte identical to the
     published CSVs.
  2. Recompute every verified record with the primary NumPy path and compare it
     with the published record.
  3. Recompute everything a second time with standard-library Python only, and
     assert agreement with the published records to 2e-06.

Stages 1 and 2 run inside a temporary copy of this directory, so nothing here is
ever written to. After a run, ``sha256sum -c SHA256SUMS`` still passes and
``git status`` is still clean.

Two fields are compared by rule rather than by byte equality, and the reason is
printed:

  * ``primary_environment`` records the interpreter and NumPy version that wrote
    a record, which differs from one machine to another.
  * ``source_unit5_result_sha256`` in the Unit 10 record is the SHA-256 of the
    Unit 5 record file as bytes, so it moves whenever that file's recorded
    environment line moves. It is checked as a pointer instead: in each tree it
    must equal the hash of the Unit 5 record sitting beside it.

Everything else is compared byte for byte, including the two files that no
generator produces: the replayed engagement column and the addenda record are
deleted from the temporary copy before the run, so stage 2 has to recreate them.

Usage:  python3 run_all.py          (add --skip-generators to leave data alone)

The base-R path is separate: Rscript run_all.R
"""

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent

UNITS_WITH_GENERATORS = [1, 2, 4, 5, 6, 7, 8, 9]
UNITS_WITH_ANALYSIS = [1, 2, 4, 5, 6, 7, 8, 9, 10]

GENERATORS = ["generate.py"] + ["generate_unit%d.py" % u for u in UNITS_WITH_GENERATORS]
PRIMARY = (["analyze.py"] + ["analyze_unit%d.py" % u for u in UNITS_WITH_ANALYSIS]
           + ["addendum_book_revision.py"])
INDEPENDENT = (["verify_independent.py"]
               + ["verify_unit%d_independent.py" % u for u in UNITS_WITH_ANALYSIS]
               + ["verify_addendum_independent.py"])

# Files that no generator produces: the addendum writes them in stage 2. They are
# deleted from the temporary copy at setup so that stage 2 has to recreate them,
# and they are then compared byte for byte like everything else.
DERIVED = ("data/unit10_latent_engagement_replay.csv",
           "expected-results/book_revision_addenda_verified_results.json")

ENVIRONMENT_KEYS = ("primary_environment", "environment", "r_environment")
POINTER_FIELDS = {"source_unit5_result_sha256": "unit5_hypertension_coaching_verified_results.json"}
UNIT10_RECORD = "unit10_cross_case_synthesis_verified_results.json"


def semantic(record):
    if not isinstance(record, dict):
        return record
    return {key: value for key, value in record.items()
            if key not in ENVIRONMENT_KEYS and key not in POINTER_FIELDS}


def load(path):
    return json.loads(path.read_text(encoding="utf-8"))


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def run(script, workdir):
    started = time.time()
    result = subprocess.run([sys.executable, str(workdir / "scripts" / script)],
                            capture_output=True, text=True)
    elapsed = time.time() - started
    if result.returncode != 0:
        print("  FAIL %s" % script)
        print(result.stdout.strip())
        print(result.stderr.strip())
        return False
    line = (result.stdout.strip().splitlines() or [""])[-1]
    print("  OK   %-38s %5.1fs  %s" % (script, elapsed, line[:96]))
    return True


def compare_data(workdir, derived=False):
    ok = True
    published = [path for path in sorted((ROOT / "data").glob("*.csv"))
                 if (("data/" + path.name) in DERIVED) == derived]
    for path in published:
        rebuilt = workdir / "data" / path.name
        if not rebuilt.is_file():
            print("  FAIL data/%s was not produced" % path.name)
            ok = False
        elif rebuilt.read_bytes() != path.read_bytes():
            print("  FAIL data/%s differs from the published file" % path.name)
            ok = False
    if ok:
        print("  OK   %s regenerated byte for byte (%d file%s)"
              % ("the replayed engagement column was" if derived else "data/",
                 len(published), "" if len(published) == 1 else "s"))
    return ok


def compare_records(workdir):
    ok = True
    published = sorted((ROOT / "expected-results").glob("*.json"))
    environment_only = []
    for path in published:
        rebuilt = workdir / "expected-results" / path.name
        if not rebuilt.is_file():
            print("  FAIL expected-results/%s was not produced" % path.name)
            ok = False
            continue
        if ("expected-results/" + path.name) in DERIVED:
            if rebuilt.read_bytes() != path.read_bytes():
                print("  FAIL expected-results/%s was not reproduced byte for byte"
                      % path.name)
                ok = False
            continue
        left, right = load(path), load(rebuilt)
        if semantic(left) != semantic(right):
            print("  FAIL expected-results/%s differs in a recorded value" % path.name)
            ok = False
        elif rebuilt.read_bytes() != path.read_bytes():
            environment_only.append(path.name)
    if ok:
        print("  OK   expected-results/ recomputed to the same values (%d records)"
              % len(published))
    if environment_only:
        print("  note %d record(s) differ only in fields derived from this machine: the "
              "recorded interpreter and NumPy version, and the Unit 10 provenance hash that "
              "points at the Unit 5 record file" % len(environment_only))
        for name in environment_only:
            print("       %s" % name)

    # provenance pointers, checked in both trees
    for tree, label in ((ROOT, "published"), (workdir, "recomputed")):
        record = load(tree / "expected-results" / UNIT10_RECORD)
        for field, target in POINTER_FIELDS.items():
            expected = sha256(tree / "expected-results" / target)
            if record.get(field) != expected:
                print("  FAIL %s tree: %s does not point at its own %s" % (label, field, target))
                ok = False
    if ok:
        print("  OK   Unit 10 provenance hash points at the Unit 5 record beside it, in both trees")
    return ok


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--skip-generators", action="store_true",
                        help="do not regenerate the CSV files")
    arguments = parser.parse_args()
    ok = True

    with tempfile.TemporaryDirectory(prefix="causal-companion-") as temporary:
        workdir = Path(temporary) / "resource"
        workdir.mkdir()
        for folder in ("data", "expected-results", "scripts"):
            shutil.copytree(ROOT / folder, workdir / folder)
        for name in DERIVED:
            (workdir / name).unlink()
        print("Working in a temporary copy; this directory is not modified.")
        print("       the %d derived file(s) were removed from the copy so that this run "
              "has to recreate them" % len(DERIVED))

        if not arguments.skip_generators:
            print("Stage 1: regenerate the synthetic datasets")
            for script in GENERATORS:
                ok &= run(script, workdir)
            ok &= compare_data(workdir)

        print("Stage 2: primary NumPy recomputation")
        for script in PRIMARY:
            ok &= run(script, workdir)
        ok &= compare_data(workdir, derived=True)
        ok &= compare_records(workdir)

    print("Stage 3: independent standard-library recomputation against the published records")
    for script in INDEPENDENT:
        ok &= run(script, ROOT)

    print()
    if ok:
        print("CAUSAL_REASONING_COMPANION_PYTHON_OK "
              "datasets=10 records=12 primary=%d independent=%d"
              % (len(PRIMARY), len(INDEPENDENT)))
        return 0
    print("CAUSAL_REASONING_COMPANION_PYTHON_FAILED")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
