#!/usr/bin/env python3
"""Generate ERRATA.md from errata/errata.json, or check that it is current.

The NEKpress companion treats every printed number as checkable against a
verified result record. Errata are held to the same standard: they are a
structured, validated record store, and the human-readable page is generated
from it rather than edited by hand.

    python3 scripts/build_errata.py            # write ERRATA.md
    python3 scripts/build_errata.py --check    # fail if ERRATA.md is stale
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "errata" / "errata.json"
OUTPUT = ROOT / "ERRATA.md"

REQUIRED_FIELDS = [
    "id",
    "reported",
    "category",
    "status",
    "work",
    "location",
    "issue",
    "resolution",
]

ID_PATTERN = re.compile(r"^ERR-\d{4}-\d{3}$")
DATE_PATTERN = re.compile(r"^\d{4}-\d{2}-\d{2}$")

STATUS_LABEL = {
    "reported": "Reported",
    "confirmed": "Confirmed",
    "fixed": "Fixed, not yet published",
    "published": "Published",
    "not-an-error": "Not an error",
    "declined": "Declined",
}

OPEN_STATUSES = {"reported", "confirmed", "fixed"}


def fail(message: str) -> None:
    raise AssertionError(message)


def load() -> dict:
    document = json.loads(SOURCE.read_text(encoding="utf-8"))
    categories = document["categories"]
    statuses = set(document["statuses"])
    seen: set[str] = set()

    for record in document["records"]:
        missing = [field for field in REQUIRED_FIELDS if field not in record]
        if missing:
            fail(f"{record.get('id', '<no id>')}: missing field(s) {missing}")
        if not ID_PATTERN.match(record["id"]):
            fail(f"{record['id']}: id must look like ERR-2026-001")
        if record["id"] in seen:
            fail(f"duplicate erratum id: {record['id']}")
        seen.add(record["id"])
        if not DATE_PATTERN.match(record["reported"]):
            fail(f"{record['id']}: reported must be YYYY-MM-DD")
        if record["category"] not in categories:
            fail(f"{record['id']}: unknown category {record['category']!r}")
        if record["status"] not in statuses:
            fail(f"{record['id']}: unknown status {record['status']!r}")

        # A numeric erratum is a disagreement with a verified record, so it must
        # name the record it contradicts. This is the whole point of the series.
        if record["category"] == "numeric" and not record.get("verified_source"):
            fail(f"{record['id']}: numeric errata must name a verified_source")

        # Anything claimed as fixed must say where the fix shipped.
        if record["status"] in {"fixed", "published"} and not record.get("fixed_in"):
            fail(f"{record['id']}: status {record['status']!r} requires fixed_in")

    return document


def render(document: dict) -> str:
    records = sorted(document["records"], key=lambda item: item["id"])
    open_count = sum(1 for item in records if item["status"] in OPEN_STATUSES)
    published = sum(1 for item in records if item["status"] == "published")
    policy = document["policy"]

    lines: list[str] = []
    add = lines.append

    add("# Errata and corrections")
    add("")
    add("<!-- Generated by scripts/build_errata.py from errata/errata.json. Do not edit by hand. -->")
    add("")
    add(
        "No book is free of errors. This page is where the errors in the NEKpress "
        "Research series are recorded, corrected, and dated — including the ones "
        "nobody has noticed yet."
    )
    add("")
    add(f"**{len(records)} recorded · {open_count} open · {published} published in a corrected edition**")
    add("")
    add(f"_Last generated {date.today().isoformat()}._")
    add("")
    add("---")
    add("")

    add("## Report something")
    add("")
    add("Four routes, all of them welcome, and none of them needs to be polite")
    add("about it.")
    add("")
    add("| If you found | Use |")
    add("| --- | --- |")
    add(
        "| A result you cannot reproduce in jamovi | "
        "[Result does not reproduce]"
        "(https://github.com/nicholaskarlson/data/issues/new?template=jamovi_output_mismatch.yml) |"
    )
    add(
        "| A wrong value, menu path, claim, or typo | "
        "[Report an erratum]"
        "(https://github.com/nicholaskarlson/data/issues/new?template=errata_report.yml) |"
    )
    add(
        "| A question about a dataset or dictionary | "
        "[Ask about the data]"
        "(https://github.com/nicholaskarlson/data/issues/new?template=data_question.yml) |"
    )
    add(
        "| An idea, or a question about using this material | "
        "[Discussions](https://github.com/nicholaskarlson/data/discussions) |"
    )
    add("")
    add(
        "Questions about your *own* research data deserve a proper answer rather "
        "than a forum thread — write to the address on "
        "[NEKpress.ca](https://nekpress.ca). "
        "[COMMUNITY.md](COMMUNITY.md) says what goes where.")
    add("")

    add("## What happens next")
    add("")
    add(
        f"- Every report is acknowledged within **{policy['acknowledgement_days']} days**."
    )
    add(
        "- A report that a **printed number is wrong** is recomputed against the "
        "verified result record for that study, and you get the recomputation — "
        "whether or not the book turns out to be wrong."
    )
    add("- Confirmed items appear on this page with a date, before any new edition ships.")
    add("- Reporters are credited by name unless they ask not to be.")
    add("")
    add(
        "Reporting that a result does not reproduce is not a complaint. It is the "
        "check this series asks readers to run, working as intended."
    )
    add("")

    add("## Categories")
    add("")
    add("| Category | Meaning |")
    add("| --- | --- |")
    for name, meaning in document["categories"].items():
        add(f"| `{name}` | {meaning} |")
    add("")

    add("## Recorded errata")
    add("")
    if not records:
        add("None recorded yet.")
        add("")
        add(
            "That is a statement about what has been reported, not a claim that the "
            "books are perfect. If you find something, the templates above are the "
            "fastest way to have it fixed."
        )
    else:
        add("| ID | Reported | Work | Location | Category | Status | Issue | Resolution |")
        add("| --- | --- | --- | --- | --- | --- | --- | --- |")
        for item in records:
            credit = item.get("credit")
            issue = item["issue"] + (f" (reported by {credit})" if credit else "")
            resolution = item["resolution"]
            if item.get("fixed_in"):
                resolution += f" Shipped in {item['fixed_in']}."
            add(
                f"| `{item['id']}` | {item['reported']} | {item['work']} "
                f"| {item['location']} | `{item['category']}` "
                f"| {STATUS_LABEL[item['status']]} | {issue} | {resolution} |"
            )
    add("")

    add("---")
    add("")
    add(
        "Follow corrections by watching this repository "
        "(**Watch → Custom → Releases**) — no address required."
    )
    add("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate errata.json and fail if ERRATA.md is out of date",
    )
    arguments = parser.parse_args()

    try:
        document = load()
        rendered = render(document)
    except (AssertionError, KeyError, json.JSONDecodeError, OSError) as error:
        print(f"ERRATA_BUILD_FAILED: {error}", file=sys.stderr)
        return 1

    if arguments.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        # The generated stamp changes daily; compare everything else.
        strip = lambda text: re.sub(r"^_Last generated .*_$", "", text, flags=re.M)
        if strip(current) != strip(rendered):
            print(
                "ERRATA_BUILD_FAILED: ERRATA.md is stale; run scripts/build_errata.py",
                file=sys.stderr,
            )
            return 1
    else:
        OUTPUT.write_text(rendered, encoding="utf-8")

    print("NEKPRESS_ERRATA_OK")
    print(f"records={len(document['records'])}")
    print(
        "open="
        f"{sum(1 for item in document['records'] if item['status'] in OPEN_STATUSES)}"
    )
    print(f"output={OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
